import bs4, requests

exampleFile = open('example.html')
exampleSoup = bs4.BeautifulSoup(exampleFile.read(), "html.parser")
elems = exampleSoup.select('#author')
# print(type(elems))
# print(elems)
# print(len(elems))
# print(type(elems[0]))
# print(elems[0].getText())
# print(str(elems[0]))
# print(elems[0].attrs)
pElems = exampleSoup.select('p')
print(len(pElems))
# print(pElems)
# print(str(pElems[1]))
# print(pElems[2].getText())
# str(pElems[0])
# pElems[0].getText()
# str(pElems[1])
